package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NTRResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Approved")
	private java.lang.Boolean approved;
	@org.kie.api.definition.type.Label(value = "Error")
	private java.lang.String error;

	public NTRResponse() {
	}

	public java.lang.Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(java.lang.Boolean approved) {
		this.approved = approved;
	}

	public java.lang.String getError() {
		return this.error;
	}

	public void setError(java.lang.String error) {
		this.error = error;
	}

	public NTRResponse(java.lang.Boolean approved, java.lang.String error) {
		this.approved = approved;
		this.error = error;
	}

}