package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class OfferItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private float amount;
	private String unit;
	private float price;

	public OfferItem() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getUnit() {
		return this.unit;
	}

	public void setUnit(java.lang.String unit) {
		this.unit = unit;
	}

	public float getAmount() {
		return this.amount;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public OfferItem(java.lang.String name, float amount,
			java.lang.String unit, float price) {
		this.name = name;
		this.amount = amount;
		this.unit = unit;
		this.price = price;
	}

}