package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Offer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.folt.OfferItem> items;

	private java.lang.String state;

	private java.lang.Integer offer_id;

	public Offer() {
	}

	public java.util.List<com.myspace.folt.OfferItem> getItems() {
		return this.items;
	}

	public void setItems(java.util.List<com.myspace.folt.OfferItem> items) {
		this.items = items;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.Integer getOffer_id() {
		return this.offer_id;
	}

	public void setOffer_id(java.lang.Integer offer_id) {
		this.offer_id = offer_id;
	}

	public Offer(java.util.List<com.myspace.folt.OfferItem> items,
			java.lang.String state, java.lang.Integer offer_id) {
		this.items = items;
		this.state = state;
		this.offer_id = offer_id;
	}

}