package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class OfferItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String unit;
	private java.lang.Double price;

	private Double amount;

	private java.lang.String name;

	public OfferItem() {
	}

	public java.lang.String getUnit() {
		return this.unit;
	}

	public void setUnit(java.lang.String unit) {
		this.unit = unit;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public OfferItem(java.lang.String unit, java.lang.Double price,
			java.lang.Double amount, java.lang.String name) {
		this.unit = unit;
		this.price = price;
		this.amount = amount;
		this.name = name;
	}

}