package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Offer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.folt.OfferItem> item;

	public Offer() {
	}

	public java.util.List<com.myspace.folt.OfferItem> getItem() {
		return this.item;
	}

	public void setItem(java.util.List<com.myspace.folt.OfferItem> item) {
		this.item = item;
	}

	public Offer(java.util.List<com.myspace.folt.OfferItem> item) {
		this.item = item;
	}

}