package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderConfirmation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean confirm;

	public OrderConfirmation() {
	}

	public java.lang.Boolean getConfirm() {
		return this.confirm;
	}

	public void setConfirm(java.lang.Boolean confirm) {
		this.confirm = confirm;
	}

	public OrderConfirmation(java.lang.Boolean confirm) {
		this.confirm = confirm;
	}

}