package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderableOffer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean orderable;

	public OrderableOffer() {
	}

	public java.lang.Boolean getOrderable() {
		return this.orderable;
	}

	public void setOrderable(java.lang.Boolean orderable) {
		this.orderable = orderable;
	}

	public OrderableOffer(java.lang.Boolean orderable) {
		this.orderable = orderable;
	}

}