package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.folt.OrderItem> items;
	private java.lang.String state;
	private com.myspace.folt.Customer customer;

	public Order() {
	}

	public java.util.List<com.myspace.folt.OrderItem> getItems() {
		return this.items;
	}

	public void setItems(java.util.List<com.myspace.folt.OrderItem> items) {
		this.items = items;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public com.myspace.folt.Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(com.myspace.folt.Customer customer) {
		this.customer = customer;
	}

	public Order(java.util.List<com.myspace.folt.OrderItem> items,
			java.lang.String state, com.myspace.folt.Customer customer) {
		this.items = items;
		this.state = state;
		this.customer = customer;
	}

}