package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderItem implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrderItem() {
    }




}