package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderConfirmation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean confirmed;

	public OrderConfirmation() {
	}

	public java.lang.Boolean getConfirmed() {
		return this.confirmed;
	}

	public void setConfirmed(java.lang.Boolean confirmed) {
		this.confirmed = confirmed;
	}

	public OrderConfirmation(java.lang.Boolean confirmed) {
		this.confirmed = confirmed;
	}

}