package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderAcceptation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean accepted;

	public OrderAcceptation() {
	}

	public java.lang.Boolean getAccepted() {
		return this.accepted;
	}

	public void setAccepted(java.lang.Boolean accepted) {
		this.accepted = accepted;
	}

	public OrderAcceptation(java.lang.Boolean accepted) {
		this.accepted = accepted;
	}

}