package com.myspace.folt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RestaurantCustomer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("ICO")
	private java.lang.String ico;

	@org.kie.api.definition.type.Label("DIC")
	private java.lang.String dic;

	@org.kie.api.definition.type.Label("StreetName")
	private java.lang.String streetName;

	@org.kie.api.definition.type.Label("PSC")
	private java.lang.String psc;

	@org.kie.api.definition.type.Label("City")
	private java.lang.String city;

	@org.kie.api.definition.type.Label("Country")
	private java.lang.String country;

	@org.kie.api.definition.type.Label("Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label("AccountNumber")
	private java.lang.String accountNumber;

	@org.kie.api.definition.type.Label("State")
	private java.lang.String state;

	@org.kie.api.definition.type.Label("Phone")
	private java.lang.String phone;

	public RestaurantCustomer() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getIco() {
		return this.ico;
	}

	public void setIco(java.lang.String ico) {
		this.ico = ico;
	}

	public java.lang.String getDic() {
		return this.dic;
	}

	public void setDic(java.lang.String dic) {
		this.dic = dic;
	}

	public java.lang.String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(java.lang.String streetName) {
		this.streetName = streetName;
	}

	public java.lang.String getPsc() {
		return this.psc;
	}

	public void setPsc(java.lang.String psc) {
		this.psc = psc;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(java.lang.String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public RestaurantCustomer(java.lang.String name, java.lang.String ico,
			java.lang.String dic, java.lang.String streetName,
			java.lang.String psc, java.lang.String city,
			java.lang.String country, java.lang.String email,
			java.lang.String accountNumber, java.lang.String state,
			java.lang.String phone) {
		this.name = name;
		this.ico = ico;
		this.dic = dic;
		this.streetName = streetName;
		this.psc = psc;
		this.city = city;
		this.country = country;
		this.email = email;
		this.accountNumber = accountNumber;
		this.state = state;
		this.phone = phone;
	}

}